# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2878f8cdbd4673ad34e39d3ee70d787469e044c18ea9f9d9987d3d85b1cf6e26140d2abeb87e6a44d494027aa7e2ff8ffe778a5f16d336f70a381898a3bcccb1

test:
  secret_key_base: 18547c999997cfc4110516f37f6744cc15efd0b8849863b928af1410853ef194ee0a8280369ffc360fcd82b12e9813ca90575aba448a9bf56839d4cb88840ab9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
